FROM debian:stable

RUN apt-get update
RUN apt-get install php-mysql -y
RUN apt-get install 7zip -y
RUN apt-get install composer -y

VOLUME /web_server

WORKDIR /web_server

CMD ["bash", "-c", "composer require lcobucci/jwt lcobucci/clock ramsey/uuid && php -S 0.0.0.0:8000 router.php"]
